fuji_username: youremail@domain.com
fuji_password: yourpassword
urls:
  X-T2: http://fnacaffiliate.com/v.i.p/camera-bodies/x-t2/
  X-Pro2: http://fnacaffiliate.com/v.i.p/camera-bodies/x-pro2/
  X-70: http://fnacaffiliate.com/v.i.p/camera-bodies/x70/
  XF23mm: http://fnacaffiliate.com/v.i.p/lenses/xf23mm/
  XF16mm: http://fnacaffiliate.com/v.i.p/lenses/xf16mm/
  XF32mm-F2: http://fnacaffiliate.com/v.i.p/lenses/xf35mm-f2-r-wr/
check_every_seconds: 600
email_notify: true
email_from: youremail@domain.com
email_to:
  - someemail@domain.com
  - 5551112222@txt.att.net
email_username: email@domain.com
email_password: emailpassword
smtp_server: smtp.gmail.com:587
loglevel: info
